### ISSUE TITLE
Star Wars Opposition

### ISSUE THREAD

**Issue by JediNarwals** [JediNarwals/TG_Missions#23]
Mod size: ~6,9GB

Star Wars Opposition is a mod that adds loads of Star Wars units, vehicles and assets to Arma 3. In the same way we used the WW2 mod I would like to use this for Divisional optionals in the future.

**Comment by JediNarwals** [comment]
This mod is a whole Arma work over! The allows for a lot of new assets that work very well with the integration into Arma. The assets are very well designed with less then a 5% drop in FPS from standard operation. This mod works well with other mods and is ready for use on the TG servers with approval.

**Comment by SullivanWorkshops** [comment]
Think this will just be a fun way for us to enjoy the game in a new way Approved
