### ISSUE TITLE
BackpackOnChest

### ISSUE THREAD

**Issue by JediNarwals** [JediNarwals/TG_Missions#8]
Requester: Mirrow
Workshop links: http://steamcommunity.com/sharedfiles/filedetails/?id=820924072

Reasons why they would be good for the community:
Currently we have the problem of unrealistic limitations to our paratrooper loadouts, the most impactful of which is being unable to take a long range radio pack. BackpackOnChest fixes this problem by letting you put an additional backpack on your chest, this limits your movement to walking. After landing you can drop the parachute and switch the chestpack to your back, regaining your mobility.

From the tiny amount of testing I've done I haven't found any errors, but this will be more thoroughly tested

**Comment by Mirrorbreak** [comment]
I have tested this during last night's 2nd Batt practice with Craig and we haven't encountered any problems. Larger scale testing might be required later on to get more results

**Comment by BayCatOne** [comment]
I see that some members use this mod and just say "It's a client side thing". But I don't like that if there's a selection of mods that we've signed off on and if client side mods can cause server issues then we should ask them to relogg from the server and remove it.

I don't mind adding this but it should be clearly stated as one of our mods if so.
Please get back to me once this is tested and confirmed. Will solve "all problems" with jumps with additional equipment.

**Comment by BayCatOne** [comment]
Status on testing?

**Comment by Mirrorbreak** [comment]
From the testing I've done I haven't found any issues with it

**Comment by BayCatOne** [comment]
Approved.

**Comment by Mirrorbreak** [comment]
Awaiting 1st batt report

**Comment by BayCatOne** [comment]
Status?

**Comment by JediNarwals** [comment]
After testing @BackpackOnChest this mod can be useful in special cases. This integrates with ACE and allows for the backpack to be placed on the chest to allow a parachute to be applied for tactical insertions. This mod causes a 0.2 - 0.5 FPS drop on client side and a 0.1 - 0.3 FPS drop on server side. In my eyes if we can get approval from the developer to put this in our TacticalGamingUniforms mod it would save a lot of hassle on the front of getting everyone to sub to the new mod. But I've been unsuccessful on getting in contact with the developer. This mod is client based and though bulky in code, does a pretty fluid process on its run. Looks good for 1st Battalion side.
