### ISSUE TITLE
Jbad

### ISSUE THREAD

**Issue by JediNarwals** [JediNarwals/TG_Missions#9]
Requester: Nazman
Link:
http://steamcommunity.com/workshop/filedetails/?id=520618345

Reason:
the Jbad mods is need because some strucctures of the maps are not from the vanilla arma, but this structures can be use also by Zeus for his mission.

**Comment by BayCatOne** [comment]
Status?

**Comment by JediNarwals** [comment]
This mod specifically started testing 2 days ago.

**Comment by JediNarwals** [comment]
This mod is dependent for Laviathan and adds a lot of objects. This mod causes a 2.5 FPS drop average server-side. Other than that the mod is good to go.

**Comment by Mirrorbreak** [comment]
Division staff approval has been given by Everest, closing issue
